version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: subastup-db
    restart: always
    environment:
      POSTGRES_DB: subastup
      POSTGRES_USER: subastup_user
      POSTGRES_PASSWORD: SubastUP2026
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
